spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8700

eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-feign
